### ISSUE TITLE
Make the task ID in local development mode longer and persistent

### ISSUE THREAD

**Issue by yangsiyu007** [microsoft/AIforEarth-API-Development#46]
When doing local development, currently an up to 4-digit number is given as the task ID. Can we make this a longer ID, since some APIs can stay in local mode for a long time?

It'd be great if the ID remains rather short, such as [https://github.com/skorokithakis/shortuuid](https://github.com/skorokithakis/shortuuid), if that won't create a problem.  

Update June 12
Another feature request: is it possible to use a remote and persistent database to store the task ID even while in local mode? For some APIs that do not need scaling up, it's useful to be able to run the container on a single VM for a long time, and not having the task IDs reset after each re-start.

**Comment by pflickin** [comment]
- Changed to guid/uuid.
- Persistent ids are now available, but only when the container is run within a local kubernetes environment and the LOCAL_BLOB_TEST_DIRECTORY matches a mounted volume.
