### ISSUE TITLE
TensorFlow example outdated

### ISSUE THREAD

**Issue by yangsiyu007** [microsoft/AIforEarth-API-Development#63]
The Dockerfile at https://github.com/microsoft/AIforEarth-API-Development/blob/master/Examples/tensorflow/Dockerfile is not compatible with the newer versions of the base Python image.

**Comment by Patil2099** [comment]
@yangsiyu007 I am new open-source can you help me in solving this issue?
Thanks!

**Comment by yangsiyu007** [comment]
@Patil2099 welcome! I think a good starting point is to update this Dockerfile to be consistent with https://github.com/microsoft/AIforEarth-API-Development/blob/master/Examples/base-py/Dockerfile, while installing the version of `tensorflow` in the current setup. To test, this [notebook](https://github.com/microsoft/AIforEarth-API-Development/blob/master/Notebooks/MLADS_Spring_2019.ipynb) has instructions for setting up the Docker container and testing the API.

**Comment by rbavery** [comment]
Hi @yangsiyu007 do you know how we can download earlier base images instead of latest? My app doesn't work now, I'm getting `python application not found` errors. I'd like to work with my existing code base rather than convert/debug it to the new base image at this time. I've tried to find tags for `mcr.microsoft.com/aiforearth/base-py` on Dockerhub and on microsoft's container registry but it doesn't seem like there is a portal where these are available. When I try `docker search mcr.microsoft.com` or the full address to the base image, other tags do not come up.

**Comment by yangsiyu007** [comment]
@rbavery sorry to hear that. Which base image did you use? What was the name, did it just have a `latest` tag?

**Comment by pflickin** [comment]
Hi Ryan.  We never take down any of our older images.  Please check https://mcrflowprodcentralus.cdn.mscr.io/mcrprod/aiforearth/base-py?P1=1569633007&P2=1&P3=1&P4=9dAjQenZNVhEw%2FCCwyNNhBnJEV9%2FStRdRNk5OsoYQr0%3D&se=2019-09-28T01%3A10%3A07Z&sig=Qvd1JiXDzKulk3PYsCz3yvjEhn7rqBZ4Tlm0lWKHu20%3D&sp=r&sr=b&sv=2015-02-21
to find the image that you need.  We will be changing the documentation to ensure that researchers do not use "latest" to avoid this in the future.  If you need ANY help restoring your state, please reach out to us and we will do whatever we can do to help.

**Comment by rbavery** [comment]
@yangsiyu007 @pflickin Thanks a bunch for the speedy response! Yep, I was using the latest tag. 

When I click on your link Patrick I get `ERROR 403: Time-Limited URL validation failed`, could you post again (maybe with a larger time validation) or email ravery@ucsb.edu? I check github at least once every day but don't get notifications and email more frequently but I could still miss the link if it expires quickly.

I think if I can get the original base image I was using I'll be good to go. I have some old images in my own container repository that work with an older version of my app but I'd like to update my build to output a detection image and detection geojson.

**Comment by rbavery** [comment]
Here is my Dockerfile for reference: https://github.com/ecohydro/CropMask_RCNN/blob/return_geo/app/Dockerfile

I adapted this Dockerfile and the rest of the app from the Tensorflow example back in May-June

**Comment by rbavery** [comment]
Hello, just pinging again to see if I can get the link reactivated to pull earlier versions than `latest` for the `base-py` image?

**Comment by rbavery** [comment]
@pflickin can I get the link to the older images?

**Comment by yangsiyu007** [comment]
@rbavery Patrick doesn't seem to be getting the notifications - I just let him know

**Comment by pflickin** [comment]
It looks like the MSFT repo changed URLs.  Please go here and click the full tag listing: https://hub.docker.com/_/microsoft-aiforearth-base-py

This link will always update to the new tag listing.
