### ISSUE TITLE
Azure container instances don't work with azure data blobs.

### ISSUE THREAD

**Issue by vasusingla619** [microsoft/AIforEarth-API-Development#65]
I can't seem to mount azure data blobs on ACI using docker, always runs into
fuse mount failed,
I can circumvent this, by passing arguments when using docker run, --cap-add SYS_ADMIN, --device /dev/fuse --security-opt apparmor:unconfined on my local, is there a way to pass these arguments to docker when launching container instance?

**Comment by pflickin** [comment]
@vasusingla619 Azure file shares can be mounted in Azure Container Instances.  Please see here: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-azure-files
